---
# Tasks file for database
 - name: mariadb structure
   become: yes
   file: path={{ item }} state=directory
   with_items:
     - "{{ data_directory }}"
     - "{{ log_directory }}"

# - name: "[DB]Install mariadb"
#   become: yes
#   docker_container:
#     name: mariadb
#     image: mariadb:latest
#     state: started
#     restart: yes
#     restart_policy: always
#     ports:
#       - 0.0.0.0:3306:3306
#     volumes:
#       - "{{ data_directory }}:/var/lib/mysql"
#       - "{{ log_directory }}:/var/log"
#     env:
#       MYSQL_ROOT_PASSWORD: "{{ mariadb_bob_password }}"
 
