---
 - name: "Install DB"
   hosts: database
   become: yes
   remote_user: bob
   pre_tasks:
     - name: Read vars from file
       become: yes
       include_vars: vars.yml
   roles:
     - common
     - database
# provisionning des serveurs web
 
 - name: "Install DB"
   hosts: web
   become: yes
   remote_user: bob
   pre_tasks:
     - name: Read vars from file
       become: yes
       include_vars: vars.yml
   roles:
     - common
     - web
