---

 - name: db for wordpress
   mysql_db: 
     login_user: root
     login_password: '{{ mariadb_root_password }}'
     login_host: "{{ db_ip }}"
     name: wordpress
     encoding: utf8
     state: present

 - name: create mariadb  user for wordpress
   mysql_user:
     login_user: bob
     login_password: '{{ mariadb_bob_password }}'
     login_host: "{{ db_ip }}"
     name: wordpress
     host: '%'
     password: '{{ mariadb_wordpress_password }}'
     priv: 'wordpress.*:ALL' 
