---
 - name: "[WEB]- install"
   hosts: web
   remote_user: bob

   vars:
      user: johnd
      domains: 
        - domain: local.dev
          php: no
          repo: https://github.com/nassafou/InstaNg.git

        - domain: demo.fr
          php: yes
        #  repo: https://github.com/nassafou/InstaNg.git
   roles:
      - common
      - nginx
      - user



