---
 - name: "[WEB]- install"
   hosts: web
   remote_user: bob

   vars:
      user: johnd
      domains: 
        - local.dev
        - demo.fr
   
   roles:
      - common
      - nginx
      - user



