---
# create item

 - name: Create directory
   become: yes
   when: item.repo is undefined
   file: path=/home/{{ user }}/{{ item }} state=directory owner={{ user }}

 - name: "Clonage du site {{ item.domain }} depuis item.repo"
   become: yes
   when: item.repo is defined
   git: dest=/home/{{ user }}/{{ item.domain }} clone=yes repo={{ item.repo }}



 - name: Link to www
   become: yes
   file: src=/home/{{ user }}/{{ item }} dest=/var/www/{{ item }} state=link

# item configuration

 - name: Create nginx configuration
   become: yes
   template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ item }}

 - name: Activate item {{ item }}
   become: yes
   file: src=/etc/nginx/sites-available/{{ item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
   notify: nginx reload 
